---
AllCops:
  DisplayCopNames:    true
  DisplayStyleGuide:  true
  StyleGuideCopsOnly: true
  TargetRubyVersion:  2.2

Style/CaseEquality:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FileName:
  Exclude:
    - lib/dry-initializer.rb

Style/Lambda:
  Exclude:
    - spec/**/*_spec.rb

Style/LambdaCall:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/Semicolon:
  Exclude:
    - spec/**/*_spec.rb

Style/SignalException:
  EnforcedStyle: semantic

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
